### PR TITLE
add logout url

### LINKED ISSUE #179: [Bug]: Logout Button not working as expected.
**Describe the bug**
The logout button is not redirecting to the callback url as it should.

**To Reproduce**
1. Stand up the iridium-core-server and iridium admin-ui locally
2. Go to 'dashboard'
3. Click on 'logout' button on the right

**Expected behaviour**
Redirect to callback url.

**Screenshots**
image

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome, Safari

**Additional context**
Follow the [run-iridium-with-docker](https://github.com/IridiumIdentity/iridium/blob/main/site/docs/3.-Running-Locally/4.run-iridium-with-docker.md)

### PR DESCRIPTION
**Pull request by joshfischer1108**
Fixes #179 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
- Added unit tests and documentation on how to test.   
- Example cURL command below:
```
curl --location --request DELETE 'http://localhost:8381/applications/localRunIdChangeForProduction/tokens' \
--header 'Authorization: Bearer {tokenValue}' \
```

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [x] `doc-complete`

### CODE REVIEW

**Comment by joshfischer1108** [comment]
@crucio-009 , I added a logout endpoint based on your issue.  Would you mind reviewing?

**Review by crucio-009 — COMMENTED** [review]
@joshfischer1108 works as expected.

**Comment by joshfischer1108** [comment]
> @joshfischer1108 works as expected.

Fantastic, thank you.  Would you mind opening a PR to account for the front-end changes required?

**Comment by crucio-009** [comment]
> Fantastic, thank you. Would you mind opening a PR to account for the front-end changes required?

@joshfischer1108 I am not very well-versed with Frontend stack maybe you can create an issue and somebody else will pick it up.

**Pull request merged**
