### PR TITLE
Issue 173 add lombok

### LINKED ISSUE #173: Add lombok to Iridium
**Is your feature request related to a problem? Please describe.**
We'd like to use a way to generate getters/setters and builder functions. 

**Describe the solution you'd like**
I'd like to use [Lombok](https://projectlombok.org/) 

**Describe alternatives you've considered**

n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by zhajikun**
Fixes #173 add lombok to entity classes.

Main Issue: #xyz

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by joshfischer1108** [comment]
@zhajikun , `main` had it's history rewritten.  You will most likely delete your fork's version of `main`, pull it down from upstream, create a new branch of your fork's `main`, and re-add your changes.  I apologize for this inconvenience. 


I also noticed the build is broken as well. Let me know if I can help in any way.

**Comment by zhajikun** [comment]
Sure. Will do as you suggested.

**Comment by zhajikun** [comment]
@joshfischer1108  Fixed PR as you suggested. Recloned your main branch, and PR back.

**Comment by joshfischer1108** [comment]
NOTE: Do not merge this PR.  It is being discussed [here](https://github.com/orgs/IridiumIdentity/discussions/180).

**Pull request closed without merging**
